# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUJ2_CipSaGbrTYK5_OFHtxEvfXOEDDt
"""

import pandas as pd

df = pd.read_csv("players_over_25kmh.csv")

SPRINT_THRESHOLD = 7.0

df["is_sprint"] = df["speed_kmh"] > SPRINT_THRESHOLD

segments = []
for player_id, player_data in df.groupby("player_id"):
    sprinting = False
    start_frame = None

    for idx, row in player_data.iterrows():
        if row["is_sprint"] and not sprinting:
            sprinting = True
            start_frame = row["frame_id"]
        elif not row["is_sprint"] and sprinting:
            sprinting = False
            end_frame = row["frame_id"] - 1
            segments.append([player_id, start_frame, end_frame])

    if sprinting:
        segments.append([player_id, start_frame, player_data["frame_id"].iloc[-1]])

sprint_segments = pd.DataFrame(segments, columns=["player_id", "start_frame", "end_frame"])

sprint_segments.to_csv("flagged_sprints.csv", index=False)

print("Flagged sprint segments saved to flagged_sprints.csv")
print(sprint_segments.head())

