# pipeline_config.yaml

# Classes
class_map:
  coco_person: 0   # -> player
  coco_ball: 32    # -> sports ball
  ours:
    player: 0
    ball: 1

# Root of your dataset repo
root: "C:/Users/bazil/Videos/SIT 374/AFL_Dataset"

# Each CVAT YOLO export (unzipped) that has images/ and labels/
manual_clips:
  - "manual_clips/kick_01"
  - "manual_clips/mark_02"
  - "manual_clips/tackle_03"

# Where the pipeline writes outputs
dataset:
  images: "dataset/images"
  labels_manual: "dataset/labels/manual"
  labels_auto: "dataset/labels/auto_coco"
  labels_remap: "dataset/labels/auto_remap"
  labels_dense: "dataset/labels/dense"
  viz: "dataset/viz_dense"
  data_yaml: "dataset/data.yaml"

# YOLO predict (auto-detect) settings
yolo:
  imgsz: 1280
  conf: 0.25
  classes: [0, 32]   # COCO person, sports ball

# Merge settings
merge:
  iou_thr: 0.3
  draw_preview: true
