version: "3.9"
services:
  mongo:
    image: mongo:4.2.23
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: on-failure
    volumes:
      - ./MQTT_broker_mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  sensor:
    build:
      context: ./Data_collection
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3001-3501:3000"
    links:
      - mosquitto
    depends_on:
      - mosquitto

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: on-failure
    container_name: server
    ports:
      - "3000:3000"
    links:
      - mosquitto
      - mongo
      - kafka
    depends_on:
      - mosquitto
      - mongo
      - kafka

  mongo_express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    restart: on-failure
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    links:
      - mongo
    depends_on:
      - mongo

  model_analysis:
    build:
      context: ./Models_analysis
      dockerfile: Dockerfile
    restart: on-failure
    container_name: models_analysis
    ports:
      - "8010:8010"
    depends_on:
      - kafka
    links:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: on-failure


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPIC_AUTO_CREATE: true
    restart: on-failure
